[project]
name = "ai-bootcamp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pydantic-ai>=1.11.0",
    "qdrant-client[fastembed]>=1.15.1",
    "requests>=2.32.5",
]
